Lesson10
ioRango9/it-academy-java-course pull request #10
Opened 2022-06-27 22:20 UTC by ioRango9

2022-06-28 13:31 UTC, maximtereshchenko requested changes

2022-06-28 13:31 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +    public void addAbbreviations(String abbreviation, String explanation, Map<String, String> map) {
Я в задании писал, как должны выглядеть сигнатуры методов. Сделай приватное поле у класса private M<String,String> map = new HashMap<>();

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +                return true;
есть метод containsKey у карты

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +                return entry.getValue();
есть метод get у карты

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        System.out.println("All abbreviations = " + map.keySet());
сделай по аналогии с другими похожими метода в этом классе: пусть все аббревиатуры печатаются на отдельной строке

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +            if (entry.getValue().equals(text)) {
надо чтобы аббревиатура содержала текст, а не равнялась ему. Т.е. это метод для поиска по частичному совпадению

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        // По условию не понял, как метод должен работать
предыдущий метод печатает аббревиатуры, которые содержат текст. Этот метод напечатает расшифровки, которые содержат указанный текст. Например:
Abbreviations abbreviations = new Abbreviations();
abbreviations.addAbbreviations("A","this is a");
abbreviations.addAbbreviations("AA","this is aa");
abbreviations.addAbbreviations("B","this is b");
abbreviations.printAbbreviationsWhere("A"); // prints 'A', 'AA'
abbreviations.printExplanationOfAbbreviationsWhere("b"); // prints 'this is b'

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        Abbreviations AAndE = new Abbreviations();
названия переменных в camelCase с маленькой буквы. И название получше бы..

2022-06-28 13:31 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Task2.java
> +        return sums / counter;
Теоретически среднее будет рассчитано неправильно, без дробной части: среднее для 4, 5 будет 4.0, вместо 4.5

2022-07-10 09:05 UTC, Xini1 requested changes

2022-07-10 09:05 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        for (String check : map.keySet()) {
Прочитай, что делает метод contains key. Тебе не нужно итерироваться по ключам

2022-07-10 09:05 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        for (String check : map.keySet()) {
Здесь тоже не нужно итерироваться по ключам. Здесь хватит всего лишь map.get(abbreviation);

2022-07-10 09:05 UTC, Xini1 commented on src/main/java/by/it_academy/lesson10/Abbreviations.java
> +        String[] arrayText = text.split(" ");
Я задумывал этот метод, как поиск по частному совпадению среди аббревиатура. Например: если сначала сделать addAbbreviation ("veryLongAbbreviation", "whatever"); и потом printAbbreviationWhere("very"); напечатает veryLongAbbreviation. Твой метод, я так понял работает так: если сначала сделать addAbbreviation ("a b", "whatever"); и потом printAbbreviationWhere("a b c"); напечатает a b. 

Предлагаю, либо сделать метод для частного поиска, либо поправь свой метод, потому что мне кажется для примера выше он напечатает a b a b (т.е. два раза)

2022-07-10 14:52 UTC, merged