Lesson11
ioRango9/it-academy-java-course pull request #11
Opened 2022-07-10 20:16 UTC by ioRango9

2022-07-10 20:17 UTC, ioRango9 commented
Криво вроде, по ходу буду править

2022-07-12 17:00 UTC, Xini1 requested changes
Пересмотри свой дизайн классов сенсоров. Должен быть стандартный сенсор, который всегда включен и его метод int read(); всегда возвращает то число, которое передали ему в конструктор при создании. Должен быть температурный сенсор, его можно включить и выключить, read возвращает число от -30 до 30, либо бросает исключение, если сенсор выключен. Должен быть средний сенсор, его задача управлять другими сенсорами, сам он ничего не делает, а делегирует работу сенсорам под его управлением. Его метод void addSensor(Sensor toAdd), позволяет добавить любой объект, который реализует интерфейс Sensor, в список сенсоров, которыми управляет (включает, выключает, считывает показания и считает среднее) AverageSensor.
Не стоит пихать наследование туда, где оно не нужно

2022-07-12 17:00 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson11/IllegalStateException.java
> +public class IllegalStateException extends RuntimeException {
IllegalStateException уже есть в java. Нет необходимости создавать свой класс

2022-07-12 17:00 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson11/Sensor.java
> +    double read();
Я ж писал в задании как должны выглядеть сигнатуры методов. В данном случае int read()

2022-07-12 17:00 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson11/StandardSensor.java
> +    private static int sensorTurn = 1;
Зачем здесь static?

2022-07-12 17:00 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson11/StandardSensor.java
> +        return getSensorTurn() == 1;
Если sensorTurn всегда 1, то почему бы не заменить на return true?

2022-07-12 17:00 UTC, Xini1 commented on src/main/java/by/it_academy/lesson11/StandardSensor.java
> +            System.out.println(e.getMessage());
Зачем бросать и ловить исключение, если твой код try {...} catch (...) {...} делает абсолютно то же самое, что и System.out.println("message");

2022-07-12 17:00 UTC, Xini1 commented on src/main/java/by/it_academy/lesson11/StandardSensor.java
> +        return getReadSensorInfo();
Почему в одном случае возвращаем readSensorInfo, а в другом sensorTurn?

2022-07-12 17:00 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson11/StandardSensor.java
> +            sensorInfo = "sensor is on";
Этот сенсор не может быть выключен же, всегда включен

2022-07-12 17:00 UTC, Xini1 commented on src/main/java/by/it_academy/lesson11/AverageSensor.java
> +    private static double averageReadInfoSensor;
Зачем эти поля static?

2022-07-12 17:00 UTC, Xini1 commented on src/main/java/by/it_academy/lesson11/AverageSensor.java
> +    public void addSensor(int readSensorInfo) {
Я в задании писал, что сигнатура метода выглядит по другому: void addSensor(Sensor toAdd)

2022-07-12 18:33 UTC, ioRango9 commented
состояние сенсора тоже через конструктор передавать?

2022-07-12 19:15 UTC, Xini1 commented
> состояние сенсора тоже через конструктор передавать?

Это нужно только для StandardSensor

2022-07-12 19:18 UTC, Xini1 commented
> состояние сенсора тоже через конструктор передавать?

А если ты про вкл/выкл, то в задании написано, что стандартный включен всегда, температурный изначально при создании включен, а состояние среднего зависит от сенсоров под его контролем

2022-08-08 15:47 UTC, merged